#!/usr/bin/env python3
"""
Generate a Goldberg-polyhedron sphere (hexagons + 12 pentagons) as OpenSCAD.

This is the panel pattern of the main spherical radome at Teufelsberg: mostly
hexagonal panels with twelve pentagons woven in - a "soccer ball" tiling, i.e.
the dual of a geodesic (subdivided-icosahedron) sphere.

Topology is computed here; the emitted `geosphere.scad` keeps R and the seam
width as live parameters and builds the solid as a union of pyramids
(center -> inset panel), so a recessed groove opens along every panel border.

Usage:
    python3 generate_goldberg.py [frequency] > geosphere.scad
    (frequency defaults to 3; higher = more, smaller hexagons)
"""
import math
import sys
from collections import defaultdict

FREQ = int(sys.argv[1]) if len(sys.argv) > 1 else 3


def norm(p):
    l = math.sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2])
    return (p[0] / l, p[1] / l, p[2] / l)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


# --- base icosahedron (consistent outward winding) -----------------------
phi = (1 + 5 ** 0.5) / 2
IV = [(-1, phi, 0), (1, phi, 0), (-1, -phi, 0), (1, -phi, 0),
      (0, -1, phi), (0, 1, phi), (0, -1, -phi), (0, 1, -phi),
      (phi, 0, -1), (phi, 0, 1), (-phi, 0, -1), (-phi, 0, 1)]
IF = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
      (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
      (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
      (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]

# --- subdivide to a geodesic sphere, with vertex dedup -------------------
verts = []          # unit-length direction vectors
vindex = {}


def add_vertex(p):
    p = norm(p)
    key = (round(p[0], 6), round(p[1], 6), round(p[2], 6))
    if key in vindex:
        return vindex[key]
    idx = len(verts)
    verts.append(p)
    vindex[key] = idx
    return idx


faces = []          # triangles as vertex-index triples (kept CCW/outward)
f = FREQ
for tri in IF:
    A, B, C = IV[tri[0]], IV[tri[1]], IV[tri[2]]
    grid = {}
    for i in range(f + 1):
        for j in range(f + 1 - i):
            p = (A[0] * (f - i - j) + B[0] * i + C[0] * j,
                 A[1] * (f - i - j) + B[1] * i + C[1] * j,
                 A[2] * (f - i - j) + B[2] * i + C[2] * j)
            grid[(i, j)] = add_vertex(p)
    for i in range(f):
        for j in range(f - i):
            faces.append((grid[(i, j)], grid[(i + 1, j)], grid[(i, j + 1)]))
            if j < f - i - 1:
                faces.append((grid[(i + 1, j)], grid[(i + 1, j + 1)], grid[(i, j + 1)]))

# --- dual: each geodesic vertex becomes a hexagon/pentagon panel ---------
fcent = [norm(((verts[a][0] + verts[b][0] + verts[c][0]) / 3,
               (verts[a][1] + verts[b][1] + verts[c][1]) / 3,
               (verts[a][2] + verts[b][2] + verts[c][2]) / 3))
         for (a, b, c) in faces]

incident = defaultdict(list)
for fi, (a, b, c) in enumerate(faces):
    incident[a].append(fi)
    incident[b].append(fi)
    incident[c].append(fi)


def tangent_basis(n):
    ref = (0, 0, 1) if abs(n[2]) < 0.9 else (1, 0, 0)
    u = norm(cross(n, ref))
    w = cross(n, u)
    return u, w


panels = []          # each panel = ordered list of unit-dir corners
for vi in range(len(verts)):
    n = verts[vi]
    u, w = tangent_basis(n)
    fis = incident[vi]
    fis = sorted(fis, key=lambda fi: math.atan2(dot(fcent[fi], w), dot(fcent[fi], u)))
    panels.append([fcent[fi] for fi in fis])

pent = sum(1 for p in panels if len(p) == 5)
hexa = sum(1 for p in panels if len(p) == 6)

# --- emit OpenSCAD -------------------------------------------------------
def vec(p):
    return "[%.6f, %.6f, %.6f]" % p


out = []
out.append("/*")
out.append("  Goldberg-polyhedron sphere (Teufelsberg main-radome pattern).")
out.append("  Units: millimeters.  GENERATED by generate_goldberg.py - edit that, not this.")
out.append("")
out.append("  A SOLID ball whose surface is tiled with %d hexagons and %d pentagons" % (hexa, pent))
out.append("  (the classic soccer-ball / geodesic-radome pattern - the dual of a")
out.append("  subdivided icosahedron). Panels vary slightly in shape, matching the")
out.append("  hexagonal paneling of the spherical radome at Teufelsberg in Berlin.")
out.append("")
out.append("  Solid, not a shell: built as the union of pyramids from the center out")
out.append("  to each panel. Every panel is shrunk toward its own center by `seam`,")
out.append("  so a real recessed groove opens along every panel border (visible in any")
out.append("  viewer and in a print).  Regenerate at another frequency with:")
out.append("      python3 generate_goldberg.py <freq> > geosphere.scad")
out.append("*/")
out.append("")
out.append("R    = 30;    // sphere radius (mm)")
out.append("seam = 0.10;  // panel seam width as a fraction of each panel (0 = no grooves)")
out.append("")
out.append("function vsum(v, i = 0) = i >= len(v) ? [0, 0, 0] : v[i] + vsum(v, i + 1);")
out.append("")
out.append("module panel(dirs) {")
out.append("  pts = [for (d = dirs) d * R];")
out.append("  c   = vsum(pts) / len(pts);")
out.append("  ins = [for (p = pts) p + (c - p) * seam];   // inset -> seam groove")
out.append("  eps = R / 5000;")
out.append("  hull() {")
out.append("    sphere(eps, $fn = 4);                     // apex at the center")
out.append("    for (p = ins) translate(p) sphere(eps, $fn = 4);")
out.append("  }")
out.append("}")
out.append("")
out.append("panels = [")
for p in panels:
    out.append("  [" + ", ".join(vec(c) for c in p) + "],")
out.append("];")
out.append("")
out.append("for (f = panels) panel(f);")
out.append("")

sys.stdout.write("\n".join(out))
sys.stderr.write("Goldberg freq=%d: %d panels (%d hexagons + %d pentagons)\n"
                 % (FREQ, len(panels), hexa, pent))
