#!/usr/bin/env python3
"""
Generate an IRREGULAR geodesic triangulated sphere as OpenSCAD, with a RAISED
rim (bortik) along every triangle edge instead of recessed grooves.

A plain subdivided icosahedron looks too crystalline: within each of the 20
faces the triangles form a uniform grid. Real geodesic radome domes read as
*less regular* - triangle size and shape vary. We take the geodesic mesh (which
keeps the pentagon/hexagon node structure of a real dome) and jitter every
interior vertex tangentially before projecting back onto the sphere. The 12
icosahedron corners are pinned so the pentagon nodes stay clean.

The body is a solid ball; the triangle pattern is shown by a network of RAISED
struts standing proud of the surface, with a small hub at every node - like the
frame of the real dome. No gaps between panels.

Usage:  python3 generate_triangulated.py [freq] [jitter] > geosphere.scad
        freq   default 4  (geodesic frequency; 3..6 sensible)
        jitter default 0.35 (tangential offset as a fraction of local edge)
"""
import math
import random
import sys

FREQ = int(sys.argv[1]) if len(sys.argv) > 1 else 4
JIT = float(sys.argv[2]) if len(sys.argv) > 2 else 0.35
random.seed(1234)


def norm(p):
    l = math.sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2])
    return (p[0] / l, p[1] / l, p[2] / l)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def scale(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


# --- base icosahedron ----------------------------------------------------
phi = (1 + 5 ** 0.5) / 2
IV = [(-1, phi, 0), (1, phi, 0), (-1, -phi, 0), (1, -phi, 0),
      (0, -1, phi), (0, 1, phi), (0, -1, -phi), (0, 1, -phi),
      (phi, 0, -1), (phi, 0, 1), (-phi, 0, -1), (-phi, 0, 1)]
IF = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
      (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
      (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
      (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]
IVn = [norm(v) for v in IV]

# --- subdivide with vertex dedup -----------------------------------------
verts = []
vindex = {}


def add_vertex(p):
    p = norm(p)
    key = (round(p[0], 6), round(p[1], 6), round(p[2], 6))
    if key in vindex:
        return vindex[key]
    idx = len(verts)
    verts.append(p)
    vindex[key] = idx
    return idx


faces = []
f = FREQ
for tri in IF:
    A, B, C = IV[tri[0]], IV[tri[1]], IV[tri[2]]
    grid = {}
    for i in range(f + 1):
        for j in range(f + 1 - i):
            p = (A[0] * (f - i - j) + B[0] * i + C[0] * j,
                 A[1] * (f - i - j) + B[1] * i + C[1] * j,
                 A[2] * (f - i - j) + B[2] * i + C[2] * j)
            grid[(i, j)] = add_vertex(p)
    for i in range(f):
        for j in range(f - i):
            faces.append((grid[(i, j)], grid[(i + 1, j)], grid[(i, j + 1)]))
            if j < f - i - 1:
                faces.append((grid[(i + 1, j)], grid[(i + 1, j + 1)], grid[(i, j + 1)]))

# --- jitter interior vertices tangentially -------------------------------
edge_len = 1.0514622 / f


def is_corner(v):
    return any(abs(v[0] - c[0]) < 1e-6 and abs(v[1] - c[1]) < 1e-6 and abs(v[2] - c[2]) < 1e-6
               for c in IVn)


jittered = []
for v in verts:
    if is_corner(v):
        jittered.append(v)
        continue
    n = v
    ref = (0, 0, 1) if abs(n[2]) < 0.9 else (1, 0, 0)
    u = norm(cross(n, ref))
    w = cross(n, u)
    ang = random.uniform(0, 2 * math.pi)
    mag = JIT * edge_len * random.uniform(0.25, 1.0)
    off = add(scale(u, math.cos(ang) * mag), scale(w, math.sin(ang) * mag))
    jittered.append(norm(add(v, off)))
verts = jittered

# --- unique edges --------------------------------------------------------
edge_set = set()
for (a, b, c) in faces:
    for (x, y) in ((a, b), (b, c), (c, a)):
        edge_set.add((min(x, y), max(x, y)))
edges = sorted(edge_set)

# --- ensure each face is wound for OpenSCAD (clockwise seen from outside) -
def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


oriented = []
for (a, b, c) in faces:
    va, vb, vc = verts[a], verts[b], verts[c]
    n = cross((vb[0] - va[0], vb[1] - va[1], vb[2] - va[2]),
              (vc[0] - va[0], vc[1] - va[1], vc[2] - va[2]))
    # OpenSCAD wants the right-hand normal pointing INWARD (dot with outward va < 0)
    oriented.append((a, c, b) if dot(n, va) > 0 else (a, b, c))
faces = oriented

# --- emit OpenSCAD -------------------------------------------------------
def vec(p):
    return "[%.6f, %.6f, %.6f]" % p


out = []
out.append("/*")
out.append("  Irregular geodesic sphere - filled triangle panels + RAISED frame")
out.append("  (Teufelsberg triangular-radome pattern).")
out.append("  Units: millimeters.  GENERATED by generate_triangulated.py - edit that, not this.")
out.append("")
out.append("  The surface is %d filled triangular panels (a closed faceted shell - the space" % len(faces))
out.append("  bounded by the triangles is filled, so it is opaque, not see-through). On top runs")
out.append("  a network of RAISED round struts along every one of the %d edges, with a hub at" % len(edges))
out.append("  each of the %d nodes - the frame of the real dome. Vertices are jittered so the" % len(verts))
out.append("  triangles vary in size/shape (less regular than a uniform grid).")
out.append("")
out.append("  Renders fast with the Manifold backend (see README). Regenerate with:")
out.append("      python3 generate_triangulated.py <freq> <jitter> > geosphere.scad")
out.append("*/")
out.append("")
out.append("R    = 15;    // sphere radius (mm)")
out.append("rim  = 0.45;  // strut radius (mm) -> raised border thickness")
out.append("node = 0.65;  // hub radius at each vertex (mm); set = rim to disable distinct hubs")
out.append("strut_fn = 24;   // strut/hub roundness (segments); higher = rounder")
out.append("")
out.append("fill = true;  // true = filled opaque triangle panels; false = hollow see-through cage")
out.append("")
out.append("verts = [")
for v in verts:
    out.append("  %s," % vec(v))
out.append("];")
out.append("")
out.append("faces = [")
for (a, b, c) in faces:
    out.append("  [%d, %d, %d]," % (a, b, c))
out.append("];")
out.append("")
out.append("edges = [")
for (a, b) in edges:
    out.append("  [%d, %d]," % (a, b))
out.append("];")
out.append("")
out.append("module strut(i, j) {")
out.append("  hull() {")
out.append("    translate(verts[i] * R) sphere(rim, $fn = strut_fn);")
out.append("    translate(verts[j] * R) sphere(rim, $fn = strut_fn);")
out.append("  }")
out.append("}")
out.append("")
out.append("union() {")
out.append("  if (fill) polyhedron(points = [for (p = verts) p * R], faces = faces);  // filled panels")
out.append("  for (e = edges) strut(e[0], e[1]);                          // raised borders")
out.append("  for (v = verts) translate(v * R) sphere(node, $fn = strut_fn);  // hubs")
out.append("}")
out.append("")

sys.stdout.write("\n".join(out))
sys.stderr.write("filled-panels freq=%d jitter=%.2f: %d triangles, %d struts, %d nodes\n"
                 % (FREQ, JIT, len(faces), len(edges), len(verts)))
