#!/usr/bin/env python3
"""
Generate an IRREGULAR geodesic triangulated sphere as OpenSCAD.

A plain subdivided icosahedron looks too crystalline: within each of the 20
faces the triangles are a perfectly uniform grid. Real geodesic radome domes
read as *less regular* - triangle size and shape vary. We reproduce that by
taking the geodesic mesh (which keeps the pentagon/hexagon node structure of a
real dome) and jittering every interior vertex tangentially before projecting
back onto the sphere. The 12 icosahedron corners are pinned so the pentagon
nodes stay clean, exactly like the photographed dome.

The emitted geosphere.scad keeps R and the seam width live, and builds the solid
as a union of wedges (center -> triangle) with each triangle inset so a groove
opens along every edge.

Usage:  python3 generate_triangulated.py [freq] [jitter] > geosphere.scad
        freq   default 4  (geodesic frequency; 3..6 sensible)
        jitter default 0.38 (tangential offset as a fraction of local edge)
"""
import math
import random
import sys
from collections import defaultdict

FREQ = int(sys.argv[1]) if len(sys.argv) > 1 else 4
JIT = float(sys.argv[2]) if len(sys.argv) > 2 else 0.38
random.seed(1234)


def norm(p):
    l = math.sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2])
    return (p[0] / l, p[1] / l, p[2] / l)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def scale(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


# --- base icosahedron ----------------------------------------------------
phi = (1 + 5 ** 0.5) / 2
IV = [(-1, phi, 0), (1, phi, 0), (-1, -phi, 0), (1, -phi, 0),
      (0, -1, phi), (0, 1, phi), (0, -1, -phi), (0, 1, -phi),
      (phi, 0, -1), (phi, 0, 1), (-phi, 0, -1), (-phi, 0, 1)]
IF = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
      (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
      (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
      (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)]
IVn = [norm(v) for v in IV]

# --- subdivide with vertex dedup -----------------------------------------
verts = []
vindex = {}


def add_vertex(p):
    p = norm(p)
    key = (round(p[0], 6), round(p[1], 6), round(p[2], 6))
    if key in vindex:
        return vindex[key]
    idx = len(verts)
    verts.append(p)
    vindex[key] = idx
    return idx


faces = []
f = FREQ
for tri in IF:
    A, B, C = IV[tri[0]], IV[tri[1]], IV[tri[2]]
    grid = {}
    for i in range(f + 1):
        for j in range(f + 1 - i):
            p = (A[0] * (f - i - j) + B[0] * i + C[0] * j,
                 A[1] * (f - i - j) + B[1] * i + C[1] * j,
                 A[2] * (f - i - j) + B[2] * i + C[2] * j)
            grid[(i, j)] = add_vertex(p)
    for i in range(f):
        for j in range(f - i):
            faces.append((grid[(i, j)], grid[(i + 1, j)], grid[(i, j + 1)]))
            if j < f - i - 1:
                faces.append((grid[(i + 1, j)], grid[(i + 1, j + 1)], grid[(i, j + 1)]))

# --- jitter interior vertices tangentially -------------------------------
edge = 1.0514622 / f          # mean edge length on the unit sphere


def is_corner(v):
    return any(abs(v[0] - c[0]) < 1e-6 and abs(v[1] - c[1]) < 1e-6 and abs(v[2] - c[2]) < 1e-6
               for c in IVn)


jittered = []
for v in verts:
    if is_corner(v):
        jittered.append(v)                       # pin pentagon nodes
        continue
    n = v
    ref = (0, 0, 1) if abs(n[2]) < 0.9 else (1, 0, 0)
    u = norm(cross(n, ref))
    w = cross(n, u)
    ang = random.uniform(0, 2 * math.pi)
    mag = JIT * edge * random.uniform(0.25, 1.0)
    off = add(scale(u, math.cos(ang) * mag), scale(w, math.sin(ang) * mag))
    jittered.append(norm(add(v, off)))
verts = jittered

# --- emit OpenSCAD -------------------------------------------------------
def vec(p):
    return "[%.6f, %.6f, %.6f]" % p


tris = [(verts[a], verts[b], verts[c]) for (a, b, c) in faces]

out = []
out.append("/*")
out.append("  Irregular geodesic triangulated sphere (Teufelsberg triangular-radome pattern).")
out.append("  Units: millimeters.  GENERATED by generate_triangulated.py - edit that, not this.")
out.append("")
out.append("  A SOLID ball tiled with %d triangles in a geodesic layout (pentagon nodes +" % len(tris))
out.append("  hexagonal flowers), but the vertices are jittered so triangle size and shape")
out.append("  VARY across the surface - the less-regular look of the real dome, not a uniform")
out.append("  grid.  Regenerate with:  python3 generate_triangulated.py <freq> <jitter> > geosphere.scad")
out.append("")
out.append("  Solid, not a shell: union of wedges from the center out to each triangle.")
out.append("  Each triangle is inset toward its centroid by `seam`, opening a real groove")
out.append("  along every edge (visible in any viewer and in a print).")
out.append("*/")
out.append("")
out.append("R    = 30;    // sphere radius (mm)")
out.append("seam = 0.07;  // groove width as a fraction of each triangle (0 = no seams)")
out.append("")
out.append("module wedge(dirs) {")
out.append("  pts = [for (d = dirs) d * R];")
out.append("  g   = (pts[0] + pts[1] + pts[2]) / 3;")
out.append("  ins = [for (p = pts) p + (g - p) * seam];")
out.append("  eps = R / 5000;")
out.append("  hull() {")
out.append("    sphere(eps, $fn = 4);")
out.append("    for (p = ins) translate(p) sphere(eps, $fn = 4);")
out.append("  }")
out.append("}")
out.append("")
out.append("tris = [")
for t in tris:
    out.append("  [%s, %s, %s]," % (vec(t[0]), vec(t[1]), vec(t[2])))
out.append("];")
out.append("")
out.append("for (t = tris) wedge(t);")
out.append("")

sys.stdout.write("\n".join(out))
sys.stderr.write("triangulated freq=%d jitter=%.2f: %d triangles\n" % (FREQ, JIT, len(tris)))
